### PR TITLE
[feature]: Review articles (moderator)

### PR DESCRIPTION
**Pull request by EtienneShamley**
Approve, reject & Duplicate handler features

### CODE REVIEW

**Review by theobwatson — CHANGES_REQUESTED** [review]
code looks good with great comments! however vercel built with errors, please check through the build logs and correct the issue before merge into main

**Comment by theobwatson** [comment]
@EtienneShamley may you please redo the fix? still having build issues

**Comment by EtienneShamley** [comment]
Yeah busy working on it

**Review by triona6 — APPROVED** [review]
accept and reject feature works well! needs to be fixed for vercel

**Comment by JymmieYang** [comment]
Code looks good! But still need sovle some complie bugs.

**Comment by theobwatson** [comment]
The error was completely unsolvable, we never located it. Instead, a new branch was made from the last successfully-deployed commit. See the working feature here: #8

**Pull request closed without merging**
